// Generated by tools/build_extension.py. Rebuild to change permitted servers.
export const BUILD_CONFIG = Object.freeze({
  backends: Object.freeze(["http://127.0.0.1:8765", "http://localhost:8765"]),
  defaultProvider: "local"
});
