import assert from 'node:assert/strict';
import {requestAnalysis} from '../shared/client.js';
const result={original_text:'Synthetic test',statements:[]};
const response=value=>({ok:true,json:async()=>value});
const requests=[];
const complete={job_id:'synthetic-test-job',status:'complete',result};
let running=true;
const fetcher=async(url,options)=>{
  requests.push({url,options});
  return response(running?{job_id:complete.job_id,status:'running',progress:{stages:[{id:'reading',state:'running'}]}}:complete);
};
const progress=[];
await assert.rejects(requestAnalysis({payload:{text:'Synthetic test'},fetcher,timeoutMs:20,onProgress:p=>progress.push(p)}),e=>e.code==='check_timeout');
assert.equal(requests.filter(r=>r.url.endsWith('/cancel')).length,0,'timeout must preserve job for retry');
assert.equal(progress[0].stages[0].state,'running');
running=false;
assert.deepEqual(await requestAnalysis({payload:{text:'Synthetic test'},fetcher}),result);
const payloads=requests.filter(r=>r.url==='/api/jobs').map(r=>JSON.parse(r.options.body));
assert.deepEqual(payloads[0],payloads[1],'retry preserves the job fingerprint and does not force another job');
running=true;
const controller=new AbortController();
const waiting=requestAnalysis({payload:{text:'Synthetic test'},fetcher,signal:controller.signal,onProgress:()=>controller.abort()});
await assert.rejects(waiting,e=>e.name==='AbortError');
assert.equal(requests.filter(r=>r.url.endsWith('/cancel')).length,1,'explicit Stop cancels the known job');
await assert.rejects(requestAnalysis({payload:{text:'Synthetic test'},fetcher:async()=>response({job_id:'failure',status:'failed',error:{error:'Please retry later.',code:'rate_limited'}})}),e=>e.code==='rate_limited'&&e.message==='Please retry later.');
assert.equal(requests[0].options.credentials,'same-origin');
running=false;
await requestAnalysis({backend:'https://clar.test',payload:{text:'Synthetic test'},fetcher,force:true});
assert.equal(requests.at(-1).options.credentials,'omit');
assert.equal(JSON.parse(requests.at(-1).options.body).force,true);
console.log('PASS: client timeout/resume, explicit cancellation, progress, failure, credentials and force behavior');
